# CharacterMarkdown Settings Export - Edit values and import with /cmdsettings import
# Version: 2.1.7
# Exported: 2025-11-09 20:05:26

champion:
  includeChampionDetailed: false
  includeChampionDiagram: true
  includeChampionSlottableOnly: false
content:
  includeAttributes: false
  includeChampionPoints: true
  includeCombatStats: false
  includeCrafting: true
  includeCurrency: true
  includeDLCAccess: true
  includeEquipment: false
  includeInventory: true
  includeLocation: true
  includeProgression: true
  includeQuickStats: true
  includeSkillBars: false
  includeSkills: true
  includeTableOfContents: true
core:
  activeFilter: "All"
  activeProfile: "Custom"
  chunkSize: 10000
  currentFormat: "github"
  customNotes: ""
  customTitle: "Battle Cleric"
display:
  includeAttentionNeeded: true
  includeBuildNotes: true
  includeRole: false
  showAllAchievements: true
  showAllQuests: true
  showAllRidingSkills: true
equipment:
  hideEmptySlots: false
  includeEquipmentAnalysis: false
  includeEquipmentEnhancement: true
  includeEquipmentRecommendations: false
  minEquipQuality: 0
extended:
  includeAchievements: true
  includeAchievementsDetailed: true
  includeAchievementsInProgress: false
  includeArmoryBuilds: false
  includeCollectibles: false
  includeCollectiblesDetailed: true
  includeCompanion: false
  includeGuilds: false
  includePvP: true
  includePvPStats: true
  includeQuests: false
  includeQuestsActiveOnly: true
  includeQuestsDetailed: true
  includeTitlesHousing: false
  includeUndauntedPledges: false
  includeWorldProgress: true
links:
  enableAbilityLinks: true
  enableSetLinks: true
skills:
  includeBuffs: false
  includeRidingSkills: true
  includeSkillMorphs: true
  minSkillRank: 0
  showMaxedSkills: true
visuals:
  useMultiColumnLayout: false